### ISSUE TITLE
Consider auto-merge support on PRs

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-simrel/simrel.build#103]
I haven't used it much, but auto-merge looks like it would be very well suited to the workflow of SimRel.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by akurtakov** [comment]
That would be nice addition - in reality only thing that is checked when submitting to simrel is if the build succeeds so having automerge would be one less thing to remember to check later and push.

**Comment by merks** [comment]
I'm not sure what kinds of checks one could put in place, in particular can it be restricted to check for committers?  If the mechanism allows anyone in the universe (with an Eclipse account) to contribute anything to SimRel and end up with PGP signed content of whatever they arbitrarily contributed, then I'd be a bit concerned.  I'll ask what's possible.

**Comment by merks** [comment]
@fredg02

Would it be possible to restrict auto-merge to committers?

**Comment by ruspl-afed** [comment]
> If the mechanism allows anyone in the universe

I doubt so, usually non-committers should wait until someone with committer rights will run the pipeline

**Comment by merks** [comment]
I see there is a two step process involved.  It needs to be enabled for the repo **once**, and then people with write permission can enable it for **every** specific pull request:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository#about-auto-merge

So nothing would ever be auto-merged automatically without a committer enabling that for a pull request and they committer will have to do that each and every time, so that does seem both completely safe and rather useful...

**Comment by merks** [comment]
I was surprised that I could just enable it without otterdog, but that's done now.

**Comment by netomi** [comment]
> I was surprised that I could just enable it without otterdog, but that's done now.

well, some settings you can change via the UI when you are maintainer, but you shouldnt but rather user otterdog as otherwise the config will be out of sync with the current live settings.
