### ISSUE TITLE
Provide an official stable "upcomming" repository that includes Milestone builds

### ISSUE THREAD

**Issue by laeubi** [eclipse-simrel/simrel.build#286]
I'm currently using in my IDE this updatesite:

https://download.eclipse.org/releases/latest

this results in Eclipse notify me whenever a new release is published and I can update (or wait if I feel its to risky because tomorrow is deadline for my project and I need to fix this one tiny little bug).

On the other hand, the three month cycle is probably a bit long and I generally trust that Eclipse delivers good software already in their milestones and it is good to discover any issue fast.

I therefore like to have an URL like

https://download.eclipse.org/releases/upcomming

that is a composite that behaves like this:

1. it contains the `lastest` as a child so of course any release is included
2. it contains a reference to the latest Milestone of the next release, for example M1/M2/... whenever it becomes avaiable
3. it contains a reference to the latest RC1/2/...

that way I can get automatic notifications of updates with just one URL, and can decide if I want to install them to give faster feedback, getting new features faster and so on.

**Comment by merks** [comment]
I think this is very similar to what this job does:

https://ci.eclipse.org/simrel/view/Releng%20jobs/job/simrel.releng.update_latest_repo/

I.e., modifies "latest" to compose a repo such as 2023-012 and soon 2024-03.

As soon as this job runs (immediately after the release):

https://ci.eclipse.org/simrel/view/Releng%20jobs/job/simrel.releng.setup_next_release/

it will create 2024-06 which initially composes 2024-03 until the first M1 and then 2024-06 will compose the M1 repository instead.

So if we wanted an "integration", "milestone", or "whatever-you-want-to-call-it" repo, we could compose 2024-06 into it as soon as it exists on the release day and then nothing else needs to be done with it until the next release.

This is not so much extra work to manage and I can certainly see this being useful.

**Comment by laeubi** [comment]
One important part would be that it is possible to update EPPs e.g in this example if have the rcp epp in my eclipse:

![grafik](https://github.com/eclipse-simrel/simrel.build/assets/1331477/c1a1b931-16a4-4012-b390-f3c00fb52c90)

this currently makes it impossible for example to use the ibuilds/rc builds, even though the site claims it is possible to update an eclipse installation e.g. even if I add this site here

https://download.eclipse.org/eclipse/downloads/drops4/S-4.31RC2-202402290520/

it says that no updates are found.

**Comment by merks** [comment]
That's an EPP issue that cannot be solved by SimRel.  Each product definition **includes** Platform features and locks in exactly that version from exactly the m1/m2/m3/rc1/rc2 repository against which EPP is built:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/f026141a-8ffe-466d-b76f-e0c80f75c1f7)

There is nothing we can change in the SimRel repository to change those version ranges in the EPP repository.  Only EPP can define the products differently.   And on that point, it's not as if the definition allows for significant flexibility:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/0375b175-a7f4-42ae-a5c8-8fedbc54bc29)

One could express range-based dependencies via the p2.inf, but then there is no good support for specifying the lower bound to be exactly the version against which one builds...

**Comment by laeubi** [comment]
What I'm wondering is why not have all features as root features, I don't see a reason why one want to forbid EPP users to update individual features.

**Comment by laeubi** [comment]
@merks maybe I got confused by the way I build sites are offered but I think basically for as of today one would want that

https://download.eclipse.org/releases/upcomming

is a composite of

- https://download.eclipse.org/releases/2013-12
- https://download.eclipse.org/releases/2024-03

once 2024-03 is "latest" it becomes a composite of

- https://download.eclipse.org/releases/2024-03
- https://download.eclipse.org/releases/2024-06

and so on, so I only ever need *one* site to get Milestone/Candidate/Release "latest".

**Comment by merks** [comment]
We already stopped composing multiple up sites for repositories like this one, which only ever references the latest version

https://download.eclipse.org/releases/2024-03/

(RC1 right now because RC2, while present as a child, is still invisible to the composite.)

I see no compelling reason to compose multiple repositories into an "upcoming" repository.  (I don't like the term upcoming because I've seen that term used nowhere else; terms like integration, stable, milestone are more commonly used.) 

Can you elaborate the utility of composing two repositories?  To me it seems more likely to be a point of confusing than actually helpful.  I.e., do I end up installing the latest upcoming or something older when there are two such possibilities available?  Moreover, even if someone wants that, they can use both  /latest and /upcoming directly (in their target platform). The /latest is already added to all EPP installations:

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/401e207e-964e-40a0-a458-35cb98363902)

**Comment by laeubi** [comment]
> I see no compelling reason to compose multiple repositories into an "upcoming" repository.

Maybe a composite is not needed but I don't want to add a new site every-time a new release is there, so I just wanted to add one https://download.eclipse.org/releases/whatever_coming_next_but_not_with_a_version_number and don't think about it anymore and just getting whatever will become latest sooner or later)

**Comment by merks** [comment]
Note that staging is generally behind the platform’s i-build so

**Comment by merks** [comment]
It appears that it will be simple to modify this line of this script to be passed in as an argument

https://github.com/eclipse-simrel/simrel.tools/blob/77f28dd15bcaeef799b5691d6191e239c5a8a69b/nextReleaseUtils/update_latest_repo.sh#L26

The following job would pass in `latest`:

https://ci.eclipse.org/simrel/view/All/job/simrel.releng.update_latest_repo/

And we could "clone" that job to pass `whatever-we-want-to-call-it` to reference the new not-yet-released repository that is created at the start of each release cycle.  (Or we could just parameterize the job to serve both purposes.)  So it's just a matter of deciding the name of the folder.

**Comment by laeubi** [comment]
> So it's just a matter of deciding the name of the folder.

So who are the once to decide, I would be happy with any name, and wen then should just mention it on the download page somewhere.

**Comment by merks** [comment]
By "the download page" you mean this page?

https://www.eclipse.org/downloads/packages/

I, with my god-like, dictatorial-though-benevolent powers, taking into consideration the opinions of others, make the decision.  👼  So I thought it would be nice to give others a least one business day to chime with with good suggestions.

We (EPP) could potentially add this new repository, initially disabled, via a touchpoint so that users could discover this.  Just a thought...

**Comment by laeubi** [comment]
> By "the download page" you mean this page?

Yes I marked some possible places where one can place an info (link)
![grafik](https://github.com/eclipse-simrel/simrel.build/assets/1331477/cc7d4ea3-9da8-4a53-8fd7-4f83e638e9eb)

like "How to follow latest Eclipse Development stream" or something like that.

> We (EPP) could potentially add this new repository, initially disabled, via a touchpoint so that users could discover this. Just a thought...

Sounds good, maybe even a menu item like "Enable Eclipse Release Preview features" ;-)

**Comment by merks** [comment]
My personal choice would be to use "milestone".  

That's used by https://eclipse.dev/justj/?page=tools 

![image](https://github.com/eclipse-simrel/simrel.build/assets/208716/0935df7b-403e-4811-8c3b-935624914dd8)

Which in turn is used to manage many update sites, e.g.,

https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest

But I'm keeping an open mind, though I would like to decide ASAP so I can try it out as part of my cleanup efforts:

https://github.com/eclipse-simrel/simrel.tools/issues/2

**Comment by merks** [comment]
This site had been created

- https://download.eclipse.org/releases/milestone/

It currently composes

- https://download.eclipse.org/releases/2024-03

which is currently RC1 because RC2 is hidden until tomorrow.

Tomorrow this will be created 

- https://download.eclipse.org/releases/2024-06

And then the milestone repo well be updated to compose that instead.  (And that repo will compose 2024-03 until 2024-06 M1.)

So `latest` and `milestone` are moving targets that follow the release and the upcoming release milestones (and release candidates) as they are made visible.

**Comment by laeubi** [comment]
Many thanks I'll add this to my Eclipse now, what do you think who can work on the Downloads page to make this easier to discover, so maybe even getting more people testing eclipse milestones?

**Comment by merks** [comment]
That page https://www.eclipse.org/downloads/packages/ is controlled by the Foundation Webdev team with guidance from the IDE WG which takes guidance from the Planning Council.  

There are a few things to note.  Nothing mentions this repository:

- https://download.eclipse.org/releases/latest/

Presumably because it's added automatically for EPP packages.

I think roughly 1/2 the users just click on the installer link here:

https://www.eclipse.org/downloads/

Those folks won't see anything to read.

The folks that do get to the packages page, likely don't read anything either; generally people read as little as absolutely necessary to achieve the goal.

Of the small fraction of folks who do read, we might encourage them to try out "preview features" but that is just politically-correct window dressing for "please be our beta testers".

If we really want to reach people and really want beta testers, we probably need to take a more direct, in-your-face approach.

You've probably noticed that this page is opened 4 times per year in your browser:

https://www.eclipse.org/setups/sponsor/

I can modify what's on that page very easily, but still, will people actually read what's presented?

A menu item on the Help menu is much more discoverable...

**Comment by laeubi** [comment]
Hard to tell if we do not mention it somewhere people will for sure not notice it, so maybe just at the "Related links" at laest?
