### ISSUE TITLE
FeatureNotFoundException for 'includeSources' in simrel.aggr

### ISSUE THREAD

**Issue by PatrickTasse** [eclipse-simrel/simrel.build#99]
Getting error opening simrel.aggr with Aggregator Model Editor after https://github.com/eclipse-simrel/simrel.build/pull/48.

Using Eclipse IDE 2023-09 with CBI Aggregator Editor 1.0.300 from https://www.eclipse.org/cbi/downloads/aggregatorLatest/

org.eclipse.emf.ecore.xmi.FeatureNotFoundException: Feature 'includeSources' not found. (platform:/resource/org.eclipse.simrel.build/simrel.aggr, 2, 523)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.reportUnknownFeature(XMLHandler.java:2057)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleUnknownFeature(XMLHandler.java:2021)
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.handleUnknownFeature(XMIHandler.java:172)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.setAttribValue(XMLHandler.java:2773)

**Comment by jonahgraham** [comment]
The current version is 1.1.0 and can be installed from https://download.eclipse.org/cbi/updates/p2-aggregator/tools/

I leave this open so that someone can update https://www.eclipse.org/cbi/downloads/aggregatorLatest/ to point to the above link.

Note that the [oomph setup](https://github.com/eclipse-simrel/simrel.build/blob/main/SimRel.setup) file should also be able to make the right setup and has this URL for latest: https://download.eclipse.org/cbi/updates/p2-aggregator/tools/nightly/latest

HTH

**Comment by PatrickTasse** [comment]
Thanks! I updated to CBI Aggregator Editor 1.1.0.v20220625-1449 but I get the same exception opening simrel.aggr.

**Comment by jonahgraham** [comment]
I have a 2023 version installed and it works - try the latest nightly please.

The latest milestone is the 2022 version you have installed.

@merks I think it is time to mark the latest nightly as the latest milestone - or archive of the milestone concept (alone with the older releases)

**Comment by merks** [comment]
May I ask how you got to this page?

https://www.eclipse.org/cbi/downloads/aggregatorLatest/

I.e., is there some link that directs you there?

I would have expected the main org page here directs one to use the Oomph setup

https://github.com/eclipse-simrel

**Comment by jonahgraham** [comment]
The links on the PMI for CBI end up at the old location.

**Comment by PatrickTasse** [comment]
I got there from the Downloads tab of https://projects.eclipse.org/projects/technology.cbi which leads to https://www.eclipse.org/cbi/downloads/.

**Comment by merks** [comment]
Thanks guys. Those are important places to fix/improve!!

**Comment by merks** [comment]
I talked to Fred and opened this issue:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3984

I did a milestone build so that all the latest sites will work.  (Well I tried to but then the test fail because of changes in p2 that required adjustments, which are now fixed.)

Note too that these versions a.l use EMF's forward compatibility support now such that unrecognized content is simply recorded and re-serialized as is.  I.e., exception cannot happy anymore.
